server:
  port: 8000
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #serverTimezone=GMT%2B8 表示时区,2B表示"+",+8个小时,北京属于东巴区
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 

  application:   #定义服务名称  必须定义在spring下面
    name: provider-user

mybatis-plus: #mybatis-plus整合
  type-aliases-package: com.jt.springcloud.pojo  #别名包
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰映射

eureka:
  client:   #当前服务端相对于eureka属于客户端
    service-url: 
      defaultZone: http://localhost:7000/eureka   #eureka是内部通信地址
  instance:
    instance-id: provider-user-8000                #定义微服务的名称,多个服务id必须不同
    prefer-ip-address: true                        #在页面上是否显示IP和端口  
  